/* eslint-disable no-unused-vars */
export enum FSMLoaderStates {
  INITIAL_LOADING_STATE = "INITIAL_LOADING_STATE",
  SSO_LOADING_STATE = "SSO_LOADING_STATE",
  PRE_RENDER_STATE = "PRE_RENDER_STATE",
  LOADING_COMPLETE_STATE = "LOADING_COMPLETE_STATE",
}
